### DISCUSSION TITLE
Writing to remote (s3) duckdb files?

### DISCUSSION THREAD

**Discussion by Mac-lp3** [duckdb/dbt-duckdb#518] [Q&A] [answered]
Hi,

I have been fighting with the config a bit and thought I should just ask at this point.

Is there any to enable writing to remote s3 files? 

```yaml
attach:
  - path: "s3://bronze/bronze.duckdb"
    alias: bronze
    read_only: false # get the below error even with this set
filesystems:
   - fs: s3
     anon: true
     key: "{{ env_var('S3_USER') }}"
     secret: "{{ env_var('S3_PASSWORD') }}"
```

```
Invalid Input Error: Cannot execute statement of type "CREATE" on database "bronze" which is attached in read-only mode!
```
