### DISCUSSION TITLE
Different connection string format for use with dagster

### DISCUSSION THREAD

**Discussion by macraesdirtysocks** [duckdb/dbt-duckdb#560] [General]
Im interested in some different perspectives on this.

I ran into an issue using dbt-duckdb with dagster.

The documented way of attaching to a postgres database didn't work.  However providing the connection string in this format worked:

```

dagster_dbt:
  outputs:
    prod:
      type: duckdb
      attach:
        - path: 'user=postgres_user host=postgres_analytics_db password=postgres_password port=5432 dbname=hasbeen'
          type: postgres
          alias: postgres_db
          
  target: prod


```

I opened this [issue](https://github.com/dagster-io/dagster/issues/30354) over at dagster.  Its not really an issue anymore per se but I would like ot better understand why it worked and how I can document this?
