### ISSUE TITLE
Writing to an SQLite database

### ISSUE THREAD

**Issue by Nintorac** [duckdb/dbt-duckdb#291]
Hey, great project love the versatility it offers!

I am having an issue trying to write to a SQLite database, I have the following configuration, and I get this error `SQLite databases do not support creating new schemas`.

Am I doing something stupid or is this not possible to do?

Thanks!

`dbt_project.yml`
```yaml
models:
  raddd_dbt:
    +materialized: table
    render_midis:
      +materialized: incremental
      +database: audio
```

`profiles.yml`
```yaml
raddd_dbt:
  outputs:
    dev:
      type: duckdb
      path: ../data/dev.duckdb
      threads: 1
      attach:
        - path: ../data/audio.db
          type: sqlite
  target: dev
```
