### ISSUE TITLE
external location in copy with filesystem not works

### ISSUE THREAD

**Issue by ZergRocks** [duckdb/dbt-duckdb#317]
```python
import duckdb
import fsspec

fs = fsspec.filesystem('jupyter', url='{jupyter lab endpoint}', tok='{jupyter lab token}')
conn = duckdb.connect(":memory:")
conn.register_filesystem(fs)
conn.sql(f"""
  copy(
  SELECT *
  FROM 'jupyter://work/1-12.parquet'
  ) to 'jupyter://1-13.parquet' (format 'parquet')
""")
```

The above copy query works well in my Jupiter Lab and processes the parquet in the folder to complete the writing well outside the folder

However, the `external.sql` macro in `dbt-duckdb` only reads well, and writes are done by creating a folder structure called `jupiter:` in my local file system

Maybe the maintenance processing for the `fsspec` session was not considered in the phrase that read and write create and insert and write by `temp` table, but I couldn't find the exact reason for it at this time. 

I was wondering if you could tell me how to solve this part or if you would like to reflect it in PR in the future

also same issue arrised with `sftp` filesystem(I tried)

```yaml
# profiles.yml
dbt_duckdb:
  outputs:
    dev:
      type: duckdb
      path: ':memory:'
      filesystems:
        - fs: jupyter
          url: '{jupyter lab endpoint}'
          tok: '{jupyter lab endpoint}'
      plugins:
        - module: delta
  target: dev

# dbt_project.yml
name: 'dbt_duckdb'
version: '1.0.0'
config-version: 2
profile: 'dbt_duckdb_delta'
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
clean-targets:
  - "target"
  - "dbt_packages"
models:
  dbt_duckdb_delta:
    delta-external:
      +materialized: 'external_table'
```
