### ISSUE TITLE
Support for blob storage/azure?

### ISSUE THREAD

**Issue by nfoerster** [duckdb/dbt-duckdb#318]
Does this only work for s3 or also with azure(abfs)?

```
sources:
  - name: external_source
    meta:
      external_location: "s3://my-bucket/my-sources/{name}.parquet"
    tables:
      - name: source1
      - name: source2
```

Both don't work although connection string and accountname/accountkey:
```
sources:
  - name: test
    meta:
      external_location: "azure://test/{name}/datetime.parquet"
    tables:
      - name: time
```

```
sources:
  - name: test
    meta:
      external_location: "abfs://test/{name}/datetime.parquet"
    tables:
      - name: time
```

**Comment by jwills** [comment]
They should work, that's just a string substitution-- did you configure the `azure` extension in your profiles.yml? https://duckdb.org/docs/extensions/azure.html

**Comment by nfoerster** [comment]
Thank you for fast response, I added the details in my profiles but still getting another error. Its saying `Generic MicrosoftAzure error: Account must be specified`, however the account name is part of the connection string.

```
16:13:37  1 of 1 START sql view model main.vw_dim_time ................................... [RUN]
16:13:37  Unhandled error while executing 
Generic MicrosoftAzure error: Account must be specified
16:13:37  1 of 1 ERROR creating sql view model main.vw_dim_time .......................... [ERROR in 0.06s]
16:13:37  
16:13:37  Finished running 1 view model in 0 hours 0 minutes and 0.31 seconds (0.31s).
16:13:37  
16:13:37  Completed with 1 error and 0 warnings:
16:13:37  
16:13:37    Generic MicrosoftAzure error: Account must be specified
16:13:37  
16:13:37  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
```

```
test:
  outputs:
    dev:
      type: duckdb
      path: '/tmp/dbt/dev.duckdb'
      packages-install-path: '/tmp/dbt/dbt_packages'
      extensions: 
        - azure
        - parquet
      plugins: 
        - module: delta
      settings:
        azure_storage_connection_string: AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;DefaultEndpointsProtocol=http;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;QueueEndpoint=http://127.0.0.1:10001/devstoreaccount1;TableEndpoint=http://127.0.0.1:10002/devstoreaccount1;
```

**Comment by jwills** [comment]
hey @nfoerster I deleted that comment cause it had account info on it, hope that was right

**Comment by nfoerster** [comment]
> hey @nfoerster I deleted that comment cause it had account info on it, hope that was right

Oh, no it was just azurite dummy string, so nothing sensitive.

**Comment by jwills** [comment]
ah good, sorry about that--- hrm, as you said, everything looks fine with your config basically right-- did you try putting double quotes around the `azure_storage_connection_string` property? I'm wondering if it's getting mangled somehow by the yaml parser

**Comment by nfoerster** [comment]
unfortunately still the same issue, is there anything else problematic? I found almost no examples using the AZ blobstore as external table location in the WWW, and I'm also struggling to find the possible parameters.

```
test:
  outputs:
    dev:
      type: duckdb
      path: '/tmp/dbt/dev.duckdb'
      packages-install-path: '/tmp/dbt/dbt_packages'
      extensions: 
        - azure
        - parquet
      plugins: 
        - module: delta
      settings:
        azure_storage_connection_string: "AccountName=devstoreaccount1;AccountKey=REDACTED;DefaultEndpointsProtocol=http;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;QueueEndpoint=http://127.0.0.1:10001/devstoreaccount1;TableEndpoint=http://127.0.0.1:10002/devstoreaccount1;"
  target: dev
```
