### ISSUE TITLE
use_credential_provider does not work when using a k8s cluster role binding

### ISSUE THREAD

**Issue by JRocki** [duckdb/dbt-duckdb#321]
Hello! I'm running dbt-duckdb on a k8s cluster via EKS that has a cluster role binding rather than using an IAM role. The project uses parquet files on S3 as the data source. It seems that using `use_credential_provider` does not work for role bindings as it leads to an HTTP 400 error. I can work around this, but I'm wondering if there is an alternative setting the botocore session instead of using `aws_creds = session.get_credentials().get_frozen_credentials()` as it is [here](https://github.com/duckdb/dbt-duckdb/blob/cd449e1a9bf07f713ec94177031f27cc9496322c/dbt/adapters/duckdb/credentials.py#L253C11-L253C67).

example code:
```
temp_project:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "/temp.duckdb"
      extensions:
        - httpfs
        - parquet
      use_credential_provider: aws
```
