### ISSUE TITLE
Specify format for external models globally

### ISSUE THREAD

**Issue by sergun** [duckdb/dbt-duckdb#387]
How to specify globally in yml configs (not in *.sql files) format (e.g. format="json") to be used for external models ?

**Comment by jwills** [comment]
Does this not work? https://docs.getdbt.com/reference/model-configs

**Comment by sergun** [comment]
@jwills 
Thanks! Yes, it does.

Sorry, it was my mistake. Configurations like:
```
models:
  hc:
    +materialized: external
    format: json
```
in dbt_project.yml work perfectly.
