### ISSUE TITLE
Parse Error: R2 Key ID Secret

### ISSUE THREAD

**Issue by waaronmorris** [duckdb/dbt-duckdb#420]
I am receiving a parse error for the key_id when creating an R2 secret. 

```
ddb:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: 'dev.duckdb'
      threads: 24
      extensions:
        - httpfs
        - parquet
      secrets:
        - type: r2
          key_id: "{{ env_var('CLOUDFLARE_CLIENT_ACCESS_KEY') }}"
          secret: "{{ env_var('CLOUDFLARE_CLIENT_SECRET') }}"
          account_id: "{{ env_var('CLOUDFLARE_ACCOUNT_ID') }}"
```

It seems to only get the first character from the `key_id` and throw a parse error for the remaining.
