### ISSUE TITLE
Data placed in 'main_' prefixed schema

### ISSUE THREAD

**Issue by rossbowen** [duckdb/dbt-duckdb#457]
Whenever I specify a schema, e.g. `raw`, the data gets placed in a schema prefixed with `main_`, e.g. `main_raw`.

Take [`jaffle_shop_duckdb`](https://github.com/dbt-labs/jaffle_shop_duckdb), if I specify a schema for my seeds to be placed into:

```yaml
seeds: 
  +docs:
    node_color: '#cd7f32'
  +schema: seeds
```

I'd expect data to land in `seeds.raw_customers` but instead it lands in `main_seeds.raw_customers`.
