### ISSUE TITLE
Glue integration throws 'client' referenced before assignment error in_get_glue_client() when using 'provider': 'credential_chain'

### ISSUE THREAD

**Issue by nmartinbekier** [duckdb/dbt-duckdb#475]
Related with Issue #432 :

When trying to register a model in Glue Catalog, when in `profiles.yml` I use:
```yaml
...
  secrets:
     - type: s3
        provider: credential_chain
...
```
 I get:

`UnboundLocalError: local variable 'client' referenced before assignment`

When reviewing `_get_glue_client()`, 

though it goes in within `if secrets is not None:`  , `client` doesn't get initialized as I have within `secrets` an array with the single value `[{'provider': 'credential_chain'}]`.
