### ISSUE TITLE
Unable to query attached postgres table(s)

### ISSUE THREAD

**Issue by emacallan** [duckdb/dbt-duckdb#500]
Building dbt models including tables from attached postgres instance (see below config) works fine, however when querying the following error occurs: 

```sql
-- defining the model. no issues
SELECT * FROM {{ source(<duckdb_alias>, <pg_table>) }}
```

```bash
# attempting to read from the model
duckdb db.duckdb -c "SELECT * FROM main.<model_derived_from_postgres>"
```

`Binder Error: Catalog "private" does not exist!`

profiles.yml
```yaml
prod:
  target: prod
  outputs: 
    prod: 
      type: duckdb
      path: db.duckdb

      attach:
        - path: postgresql://example:{{env_var('PGPASSWORD')}}@localhost:5432/private
          type: postgres
```

Is there any information about how to  correct my profiles.yaml config / any known workarounds? 

<details>
<summary>Alternative approaches tried</summary>
<p>

Some other things I tried:
1. sources.yml in a subfolder, referencing it using `{{ source('data', 'table1') }}`. (`database: private` tried in conjunction with profiles.yml `duckdb_alias: private` ) 

`dbt build`: ✅  
query: ❌ 

```yaml

sources: 
  - name: data
    database: private
    schema: <postgres-schema>
    tables: 
      - name: <postgres-table1>
      - name: <postgres-table2>

``` 

2. Adding duckdb_alias: <alias> to profiles.yml with different alias names without `sources.yaml`
`dbt build`: ✅ 
query: ❌ 

</p>
</details>

```bash 
dbt --version
```
>Core:
>  - installed: 1.9.1
>  - latest:    1.9.1 - Up to date!
>
>Plugins:
>  - duckdb: 1.9.1 - Up to date!
