### ISSUE TITLE
adapter.location_exists errors out when using meta.external_location in a sources.yml file

### ISSUE THREAD

**Issue by MiConnell** [duckdb/dbt-duckdb#527]
Given this sources.yml file:

```yaml
version: 2

sources:
  - name: data
    freshness:
      warn_after: {count: 24, period: hour}
      error_after: {count: 48, period: hour}
    description: Data
    tables:
      - name: addresses
        description: "{{ doc('addresses') }}"
        meta:
          external_location: ./data/addresses.parquet
```

calling the below in a sql file evaluates to false even though the file exists. 

```jinja
{% set source_name = 'data' %}
{% set table = 'addresses' %}

{%- set source_relation = source(source_name, table) -%}
{% do log(source_relation, true) %}

{# './data/addresses.parquet' #}

{%- set exists = adapter.location_exists(source_relation) -%}

{% do log(exists, true) %}

{# False #}
```

Looking at the [impl.py file](https://github.com/duckdb/dbt-duckdb/blob/d26ae6fcf2466821ef986d5147a3e2c1dc92c211/dbt/adapters/duckdb/impl.py#L97), the location is wrapped in single quotes. Printing out the query shows:

```sql
select 1 from ''./data/addresses.parquet'' where 1=0
```

and errors with 

```
Parser Error: syntax error at or near "."
```

Removing the single quotes around location fixes the error, and the location_exists evaluates to True again. 
There aren't many docs on what this macro is meant to do, but given its name I'm assuming it's for external_locations only so hoping removing the single quotes will fix this issue without causing any other problems.
