### ISSUE TITLE
Handle dbt_valid_to_current in snapshots

### ISSUE THREAD

**Issue by acirtep** [duckdb/dbt-duckdb#528]
Starting with `dbt 1.9`, there's a possibility to  configure `dbt_valid_to_current` in [snapshots](https://docs.getdbt.com/reference/resource-configs/dbt_valid_to_current), such that `valid_to` is not null. 

When `dbt_valid_to_current` is configured, `dbt-duckdb` fails to update the previous records with the update date.

### Steps to reproduce

- create an ephemeral model, `stg_test_snapshot_ephemeral`
```
{{ config(materialized='ephemeral') }}

select range as id,
       now() at time zone 'UTC' as updated_at
from range(2)
```
- define the snapshot, under `snapshots`:

```
  - name: test_snapshot
    relation: ref('stg_test_snapshot_ephemeral')
    config:
      unique_key: id
      updated_at: updated_at
      strategy: timestamp
      dbt_valid_to_current: "'9999-12-31 23:59:59'::timestamp"
```

After two executions (`dbt snapshot --select test_snapshot`), the previous records remain open:
```
select id, dbt_updated_at, dbt_valid_to from test_snapshot;
┌───────┬─────────────────────────┬─────────────────────┐
│  id   │     dbt_updated_at      │    dbt_valid_to     │
│ int64 │        timestamp        │      timestamp      │
├───────┼─────────────────────────┼─────────────────────┤
│     0 │ 2025-03-31 08:39:53.729 │ 9999-12-31 23:59:59 │
│     1 │ 2025-03-31 08:39:53.729 │ 9999-12-31 23:59:59 │
│     0 │ 2025-03-31 08:39:57.712 │ 9999-12-31 23:59:59 │
│     1 │ 2025-03-31 08:39:57.712 │ 9999-12-31 23:59:59 │
└───────┴─────────────────────────┴─────────────────────┘
```

Looking at the logs, the calculation of dbt_valid_to takes into account the default value

```
  coalesce(nullif(updated_at, updated_at), '9999-12-31'::date) as dbt_valid_to
```

, but the update on the target table filters on `DBT_INTERNAL_TARGET.dbt_valid_to is null;`.
