### ISSUE TITLE
Profile for DuckLake

### ISSUE THREAD

**Issue by esadek** [duckdb/dbt-duckdb#558]
Hi, I'm trying to use the adapter with DuckLake. I see 2c9fa8c includes some additions for DuckLake, but I am getting a runtime error. Is something missing from my profile?

`profiles.yml` file:

```yml
dbt_project:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: :memory:
      extensions:
        - ducklake
      attach:
        - path: ducklake:metadata.ducklake
```

Error:

```
uv run dbt seed
19:33:12  Running with dbt=1.9.5
19:33:12  Encountered an error:
Runtime Error
  
  dbt encountered an error while trying to read your profiles.yml file.
  
  Runtime Error
    Syntax error near line 6
    ------------------------------
    3  |   outputs:
    4  |     dev:
    5  |       type: duckdb
    6  |       path: :memory:
    7  |       extensions:
    8  |         - ducklake
    9  |       attach:
    
    Raw Error:
    ------------------------------
    mapping values are not allowed in this context
      in "<unicode string>", line 6, column 20
```
