### ISSUE TITLE
data_path in options is not treated as a path

### ISSUE THREAD

**Issue by RekunDzmitry** [duckdb/dbt-duckdb#564]
In that PR a support for arbitrary key value pairs in Attachment ATTACH options was introduced - https://github.com/duckdb/dbt-duckdb/pull/556.
It fails for a configuration like:
```
profile:
  outputs:
    dev:
      type: duckdb
      path: 'C:/data/db.duckdb'
      extensions:
        - ducklake
      attach:
        - path: ducklake:metadata.ducklake
          alias: ducklake
          options:
            data_path: 'C:/data/metadata'
      threads: 1
```
The error is - Runtime Error
  Parser Error: syntax error at or near ":"

Reason for it - data_path is not handled as a path, just as string.
Possible solution:
def to_sql(self) -> str:
   ```
 ...
    if self.options:
            handled_keys = {"type", "secret", "read_only"}
            for key, value in self.options.items():
                if key in handled_keys:
                    continue
                if isinstance(key, str) and key.lower() == "data_path":
                    parsed_data_path = self._parse_data_path(value)
                    all_options.append(f"DATA_PATH {parsed_data_path}")
                    continue
                # Format the option appropriately
                if isinstance(value, bool):
                    if value:  # Only add boolean options if they're True
                        all_options.append(key.upper())
                elif value is not None:
                    all_options.append(f"{key.upper()} {value}")
    ...

    def _parse_data_path(self, data_path: str) -> str:
        if data_path is None or data_path == ":memory:":
            return "memory"
        parsed = urlparse(data_path)
        base_file = os.path.basename(parsed.path)
        path_db = os.path.splitext(base_file)[0]

        return path_db
```
