### ISSUE TITLE
Cannot attach a remote Postgres Ducklake catalog (local DuckDB catalog works)

### ISSUE THREAD

**Issue by AlphaJack** [duckdb/dbt-duckdb#567]
Hi, in DuckDB, I can attach a postgres Ducklake catalog:

```sql
CREATE SECRET (
    TYPE postgres,
    HOST "HHH",
    PORT NNN,
    DATABASE "DDD",
    USER "UUU",
    PASSWORD "PPP"
);

INSTALL ducklake;

ATTACH 'ducklake:postgres:' AS datalake
    (DATA_PATH 'lake/');
USE datalake;
```

However, I cannot configure a proper dbt target to achieve the same.

With:

```yml
    dev:
      type: duckdb
      extensions:
        - ducklake
        - postgres
      secrets:
        - type: postgres
          host: "HHH"
          port: NNN
          user: UUU
          password: "PPP"
          database: DDD # I assume it's duckdb secrets's "DATABASE" instead of libpq's "dbname"
      attach:
        - path: "ducklake:postgres:"
          alias: datalake
          options:
            data_path: lake/storage
      database: datalake
```

I get:

```
Runtime Error
  IO Error: Failed to attach DuckLake MetaData "__ducklake_metadata_datalake" at path + "postgres:"Unable to connect to Postgres at : connection to server on socket "/tmp/.s.PGSQL.5432" failed: No such file or directory
        Is the server running locally and accepting connections on that socket?
```

With

```yml
    dev:
      type: duckdb
      extensions:
        - ducklake
        - postgres
      attach:
        - path: "ducklake:postgresql://UUU:PPP@HHH:NNN/DDD"
          alias: datalake
          options:
            data_path: lake/storage
      database: datalake
```

I get:

```
Runtime Error
  IO Error: Failed to attach DuckLake MetaData "__ducklake_metadata_datalake" at path + "postgresql://UUU:PPP@HHH:NNN/DDD"Cannot open file "postgresql://UUU:PPP@HHH:NNN/DDD": No such file or directory
```

Am I missing something?
I can successfully create a local DuckDB catalog with:

```yml
    dev:
      type: duckdb
      extensions:
        - ducklake
      attach:
        - path: "ducklake:lake/metadata.duckdb"
          alias: datalake
          options:
            data_path: lake/storage
      database: datalake
```

I am using dbt 1.9.6 and the extension from the main branch (1.9.4-dev21)

---

EDIT:

Somehow it seems to work with this format, even if I'd rather use secrets:

```yml
    dev:
      type: duckdb
      extensions:
        - ducklake
        - postgres
      attach:
        - path: "ducklake:postgres:host=HHH port=NNN user=UUU password=PPP dbname=DDD"
          alias: datalake
          options:
            data_path: lake/storage
      database: datalake

```

**Comment by jwills** [comment]
Ah apparently there is a (secret) `META_SECRET` option: https://github.com/duckdb/ducklake/discussions/169 (it should be possible to specify the meta_secret in the `options:` dict, just like you do for the `data_path`)

**Comment by AlphaJack** [comment]
Thank you for checking!
Working code:

```yml
    dev:
      type: duckdb
      extensions:
        - ducklake
        - postgres
      secrets:
        - type: postgres
          name: pg_metadata
          host: "HHH"
          port: NNN
          user: UUU
          password: "PPP"
          database: DDD
      attach:
        - path: "ducklake:postgres:"
          alias: datalake
          options:
            meta_secret: pg_metadata
            data_path: lake/storage
      database: datalake
```
